#!/usr/bin/env python3
"""Generate the translate_lookup case statement inside install.sh."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TRANSLATION_PATH = ROOT / "i18n" / "translations.json"
INSTALL_PATH = ROOT / "install.sh"
START_MARKER = "# >>> I18N LOOKUP START"
END_MARKER = "# >>> I18N LOOKUP END"


def load_translations() -> dict[str, dict[str, str]]:
    data = json.loads(TRANSLATION_PATH.read_text(encoding="utf-8"))
    if "en" not in data:
        raise SystemExit("English (en) translations are required")

    keys = set(data["en"].keys())
    for lang, entries in data.items():
        missing = keys - entries.keys()
        extra = entries.keys() - keys
        if missing:
            raise SystemExit(f"{lang} missing keys: {', '.join(sorted(missing))}")
        if extra:
            raise SystemExit(f"{lang} has extra keys not in English: {', '.join(sorted(extra))}")
    return data


def escape_value(value: str) -> str:
    replacements = [
        ("\\", "\\\\"),
        ('"', '\\"'),
        ("$", "\\$"),
        ("`", "\\`"),
        ("\n", "\\n"),
    ]
    for old, new in replacements:
        value = value.replace(old, new)
    return value


def build_case_block(data: dict[str, dict[str, str]]) -> str:
    lines = [
        "translate_lookup() {",
        "    local lang=\"$1\"",
        "    local key=\"$2\"",
        "    case \"${lang}:${key}\" in",
    ]

    for lang in sorted(data.keys()):
        for key in sorted(data["en"].keys()):
            value = escape_value(data[lang][key])
            lines.append(f"        \"{lang}:{key}\") echo \"{value}\" ;;")

    lines.append("        *) return 1 ;;")
    lines.append("    esac")
    lines.append("}")
    return "\n".join(lines)


def replace_block(content: str, new_block: str) -> str:
    if START_MARKER not in content or END_MARKER not in content:
        raise SystemExit("Translation markers not found in install.sh")
    start = content.index(START_MARKER) + len(START_MARKER)
    end = content.index(END_MARKER)
    before = content[:start]
    after = content[end:]
    return f"{before}\n# Auto-generated by scripts/generate_i18n_snippet.py\n{new_block}\n{after}"


def main() -> None:
    check_mode = "--check" in sys.argv
    data = load_translations()
    block = build_case_block(data)
    original = INSTALL_PATH.read_text(encoding="utf-8")
    updated = replace_block(original, block)

    if check_mode:
        if original != updated:
            raise SystemExit("Translation lookup block is out of date. Run the generator.")
        return

    INSTALL_PATH.write_text(updated, encoding="utf-8")
    print("Updated translation lookup block in install.sh")


if __name__ == "__main__":
    main()

